In [1]:
import numpy as np

In [2]:
def weightInitialization(n_features):
    w = 0.1*np.random.randn(1,n_features)-0.5
    b = 0
    return w.T,b

In [3]:
w,b=weightInitialization(2)
w.shape

(2, 1)

In [8]:
def sigmoid_activation(result):
    final_result = 1/(1+np.exp(-result))
    return final_result

In [9]:
sigmoid_activation(np.array([1.56,
1.19,
1.47,
]))

array([0.82635335, 0.76674106, 0.81305739])

In [10]:
def one_hotSGD(Y):
    one_hot_Y = np.zeros((Y.size, Y.max()+1))
    one_hot_Y[np.arange(Y.size), Y] = 1
    one_hot_Y = one_hot_Y.T
    return one_hot_Y

In [7]:
one_hotSGD(Y)

NameError: name 'Y' is not defined

In [32]:
def model_predict(X, Y, learning_rate, no_iterations):
    w = (0.1*np.random.randn(2,X.shape[0])-0.5)
    print('Random ws',w)
    b = 0.5
    m = X.shape[1]
    costs = []
    for i in range(no_iterations):
       
        #Prediction 
        #(1,2)(2,2)
        out=np.dot(w,X)+b
        print('out:',out)
        #(3,2)
        final_result = sigmoid_activation(out)
        print('act:',final_result)
        Y_T =Y
        cost = (-1/m)*(np.sum((Y_T*np.log(final_result)) + ((1-Y_T)*(np.log(1-final_result)))))
        print('cost',cost)
        #Gradient calculation
        diff=final_result-Y_T
        print('diff:',diff)
        #(3,2)(2,2)
        dw = (1/m)*(np.dot(diff,X.T))
        db = (1/m)*(np.sum(diff).T)
        print('dw:',dw,'db:',db)
        #weight update
        w = w - (learning_rate * (dw))
        b = b - (learning_rate * db)
        print('new w:',w,'new b:',b)
        #
        
        #if (i % 50 == 0):
           # print(cost)
    
    
    return w, b, costs

In [33]:
w, b, costs= model_predict(X, Y, 0.01, 2)

Random ws [[-0.61105875 -0.18586038]
 [-0.53500706 -0.45201076]]
out: [[-0.70072646 -0.63427282 -0.89728236]
 [-0.8984242  -0.92702602 -1.18622992]]
act: [[0.33165118 0.34654232 0.28960929]
 [0.28937443 0.28352846 0.23393389]]
cost 1.2370088576593272
diff: [[-0.66834882  0.34654232  0.28960929]
 [-0.71062557  0.28352846  0.23393389]]
dw: [[-0.02096738  0.06038992]
 [-0.10632669 -0.01772126]] db: -0.07512014104498968
new w: [[-0.61084908 -0.18646428]
 [-0.53394379 -0.45183355]] new b: 0.5007512014104499
out: [[-0.70036446 -0.63413393 -0.89711998]
 [-0.89575912 -0.92452043 -1.1832813 ]]
act: [[0.33173143 0.34657377 0.2896427 ]
 [0.28992278 0.28403772 0.23446272]]
cost 1.2367960899322865
diff: [[-0.66826857  0.34657377  0.2896427 ]
 [-0.71007722  0.28403772  0.23446272]]
dw: [[-0.02088986  0.06045557]
 [-0.10547928 -0.01696524]] db: -0.0745429578192638
new w: [[-0.61064018 -0.18706883]
 [-0.532889   -0.4516639 ]] new b: 0.5014966309886426


In [34]:
w.shape

(2, 2)

In [10]:
def predict(final_pred, m):
    y_pred = np.zeros((1,m))
    for i in range(final_pred.shape[1]):
        if final_pred[0][i] > 0.5:
            y_pred[0][i] = 1
    return y_pred

In [24]:
X= np.array([
    [1.6,1.2],
    [1.4 ,1.5],
    [1.8, 1.6],
    
]).T
X

array([[1.6, 1.4, 1.8],
       [1.2, 1.5, 1.6]])

In [25]:
Y=np.array([1,0,0]).T
Y

array([1, 0, 0])